version: "3.7"

services:
  chocotester:
    container_name: chocotester
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: D:/output
        target: C:/output
      - type: bind
        source: D:/input
        target: C:/input